resources:
- name: repo-trigger
  type: git
  check_every: 1m
  source:
    paths: ["*"]
    uri: https://github.com/sebbonnet/concourse-playground.git 
    branch: main
- name: repo
  type: git
  source:
    uri: https://github.com/sebbonnet/concourse-playground.git

jobs:
- name: hello-world-job
  plan:
  - get: repo-trigger
    trigger: true
    version: every
  - get: repo
  - task: hello-world-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      run:
        path: echo
        args: ["Hello World!"]

